name: CI/CD for pain-imputer

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn tensorflow==2.10.0 pytest
        pip install -e .
    - name: Run tests
      working-directory: ./
      env:
        PYTHONPATH: .
      run: |
        pytest tests/ --verbose

  publish-pypi:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pain-imputer/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          password: ${{ secrets.PYPI_API_TOKEN }}
